language: generic
os: linux
jobs:
  include:
    - stage: Build and Deploy
      script: >
        curl -sL "https://github.com/getzola/zola/releases/download/v0.9.0/zola-v0.9.0-x86_64-unknown-linux-gnu.tar.gz" | tar zxv
        && ./zola build
        && echo anjali.uses-light-the.me > public/CNAME
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        local_dir: public
        on:
          branch: master
