language: rust
jobs:
  include:
    - stage: Build and Deploy
      script: |
        wget –quiet -O zola.tar.gz https://github.com/getzola/zola/releases/download/v0.9.0/zola-v0.9.0-x86_64-unknown-linux-gnu.tar.gz
        echo Finished download
        tar -xvzf zola.tar.gz
        echo Finished unTar
        tree .
        ./zola/zola build
        echo Finished Build
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
        keep_history: true
        on:
          branch: master